# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
- script: kubectl config use-context all-tap-all-the-time
  displayName: 'Change to Buildservice Kube Context'

- script: |
    kp image save tbs-demo-app  --tag harbor.buildmodernapps.com/apps/tbs-demo-app:latest --local-path .
    sleep 10
    kp image list
    kp build list
    kp build logs tbs-demo-app
  displayName: 'Run TBS Build in current working directory'
