# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default



steps:
# - script: kubectl config use-context all-tap-all-the-time
#   displayName: 'Change to Buildservice Kube Context'
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'SANDBOX_SOLUTIONS_SOUTH_JR (aab93c1b-c3a9-45ed-bb90-04e0c42bb133)'
    KeyVaultName: 'kubeconfigs'
    SecretsFilter: '*'
    RunAsPreJob: true

- script: |
    export user=$(whoami)
    echo $(all-tap-all-the-time) |base64 --decode >  ~/.kube/config
    kubectl config use-context all-tap-all-the-time
    export TMC_API_TOKEN=$(TMC)
    tmc login --name Automation  --no-configure
    tmc cluster list --all
    kp image save tbs-demo-app  --tag harbor.buildmodernapps.com/apps/tbs-demo-app:latest	 --local-path .
    sleep 10
    kp image list
    kp build list
    kp build logs tbs-demo-app
  displayName: 'Run TBS Build in current working directory'
