# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: default

steps:
# - script: kubectl config use-context all-tap-all-the-time
#   displayName: 'Change to Buildservice Kube Context'
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'SANDBOX_SOLUTIONS_SOUTH_JR (aab93c1b-c3a9-45ed-bb90-04e0c42bb133)'
    KeyVaultName: 'kubeconfigs'
    SecretsFilter: '*'
    RunAsPreJob: true

- task: Docker@2
  inputs:
    containerRegistry: 'Harbor Registry'
    command: 'login'

- script: |
    mkdir -p ~/.kube/
    export user=$(whoami)
    echo $(all-tap-all-the-time) |base64 --decode >  ~/.kube/config
    kubectl config use-context all-tap-all-the-time
    tanzu apps workload apply tap-demo-app --local-path . --source-image harbor.buildmodernapps.com/apps/tap-demo-app:latest  --type web --label app.kubernetes.io/part-of=tanzu-java-web-app  --label tanzu.app.live.view="true"  --label tanzu.app.live.view.application.name="java-web" -y 
    kp image list
    kp build list
    sleep 15
    kp build logs tap-demo-app
    tanzu apps workload get tap-demo-app
  displayName: 'Run TBS Build in current working directory'
